- name: Validate required variables
  ansible.builtin.assert:
    that:
      - slurm_controller_host | length > 0
    fail_msg: "slurm_controller_host must be set"
    quiet: true

- name: Install sackd package
  ansible.builtin.apt:
    name:
      - sackd
    state: present

- name: Create systemd override directory for sackd
  ansible.builtin.file:
    path: /etc/systemd/system/sackd.service.d
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Configure sackd for configless mode
  ansible.builtin.template:
    src: sackd-configless.conf.j2
    dest: /etc/systemd/system/sackd.service.d/configless.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart sackd

- name: Start and enable sackd service
  ansible.builtin.systemd:
    name: sackd
    state: started
    enabled: yes
    daemon_reload: yes

- name: Restart sackd if slurm config changed on controller
  ansible.builtin.systemd:
    name: sackd
    state: restarted
  when: hostvars[groups['slurm_ctrl'][0]]['slurm_config_changed'] | default(false)
