---
- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true
  changed_when: true

- name: Restart cachefilesd
  ansible.builtin.service:
    name: cachefilesd
    state: restarted
