- name: Gather minimal facts for os_family detection
  ansible.builtin.setup:
    gather_subset:
      - "!all"
      - "!any"
      - distribution

- name: Create sshd_config.d directory
  ansible.builtin.file:
    path: /etc/ssh/sshd_config.d
    state: directory
    mode: '0755'
  when: sshd.host_ed25519_key is defined

- name: Remove old SSH hostkey configuration file
  ansible.builtin.file:
    path: /etc/ssh/sshd_config.d/80-custom-hostkey.conf
    state: absent
  when: sshd.host_ed25519_key is defined
  notify: Reload SSH

- name: Deploy SSH hostkey configuration
  ansible.builtin.template:
    src: "80-ssh-hostkey.conf.j2"
    dest: "/etc/ssh/sshd_config.d/80-ssh-hostkey.conf"
    owner: root
    group: root
    mode: '0644'
  when: sshd.host_ed25519_key is defined
  notify: Reload SSH

- name: Configure private host key (ed25519)
  ansible.builtin.copy:
    content: "{{ sshd.host_ed25519_key }}\n"
    dest: /etc/ssh/custom_ssh_host_ed25519_key
    owner: root
    group: root
    mode: '0600'
  when: sshd.host_ed25519_key is defined
  notify: Reload SSH

- name: Configure public host key (ed25519)
  ansible.builtin.copy:
    content: "{{ sshd.host_ed25519_key_pub }}\n"
    dest: /etc/ssh/custom_ssh_host_ed25519_key.pub
    owner: root
    group: root
    mode: '0644'
  when: sshd.host_ed25519_key_pub is defined
  notify: Reload SSH
