---
- name: reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: yes
  when: ansible_os_family != "Alpine"
  changed_when: true

- name: restart vmagent (systemd)
  ansible.builtin.systemd:
    name: "{{ vmagent_service_name }}.service"
    state: restarted
    daemon_reload: true
  when: ansible_os_family != "Alpine"
  listen: restart vmagent

- name: restart vmagent (OpenRC)
  ansible.builtin.service:
    name: "{{ vmagent_service_name }}"
    state: restarted
  when: ansible_os_family == "Alpine"
  listen: restart vmagent
