---
- name: reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: yes
  changed_when: true

- name: restart node_exporter
  ansible.builtin.systemd:
    name: "{{ node_exporter_service_name }}.service"
    state: restarted
    daemon_reload: true
