---
- name: Create ZFS datasets
  community.general.zfs:
    name: "{{ item.name }}"
    state: present
    extra_zfs_properties: "{{ item.properties | default({}) }}"
  loop: "{{ zfs_datasets }}"
  loop_control:
    label: "{{ item.name }}"
