---
- name: reload systemd user daemon
  ansible.builtin.systemd:
    daemon_reload: yes
    scope: user
  become: yes
  become_user: "{{ loki_user }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ quadlet_uid }}"
  changed_when: true

- name: restart loki
  ansible.builtin.systemd:
    name: loki.service
    state: restarted
    daemon_reload: true
    scope: user
  become: yes
  become_user: "{{ loki_user }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ quadlet_uid }}"