- name: Ensure authorized_keys for ansible user
  ansible.builtin.authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ item }}"
  loop: "{{ ansible_runner_user.ssh_authorized_keys }}"

- name: Ensure /etc/sudoers.d/95-ansible-user exists with sudo privileges
  ansible.builtin.copy:
    content: "Defaults:{{ ansible_user }} !requiretty\n{{ ansible_user }} ALL=(ALL) NOPASSWD: ALL\n"
    dest: /etc/sudoers.d/95-ansible-user
    owner: root
    group: root
    mode: "0440"
    validate: "visudo -cf %s"

- name: Ensure old sudoers files are absent
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/sudoers.d/ansible-runner-user
    - /etc/sudoers.d/ansible
    - /etc/sudoers.d/initial-user

- name: Ensure ansible user shell is /bin/bash and password is disabled
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    shell: /bin/bash
    password: "{{ ansible_runner_user.password }}"
